#spring.application.name=securityTutorial
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt
    username: root
    password: 52950
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8888
